### ISSUE TITLE
Crash when pressing escape!!!

### ISSUE THREAD

**Issue by teodorlu** [iterateno/iterbart-rofi#5]
Repro:

1. `$ iterbart`
2. press esc
3. observe:

```
Traceback (most recent call last):
  File "/home/teodorlu/.local/bin/iterbart", line 51, in <module>
    target = subprocess.check_output(["bash", "-c", f"echo {title_lines} | rofi -i -dmenu"]).decode("utf-8").strip()
  File "/home/teodorlu/.asdf/installs/python/3.9.2/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/teodorlu/.asdf/installs/python/3.9.2/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bash', '-c', 'echo "Leancast\nSimployer\nTripletex\nNotion\nOpsboka\nCV partner\nFrokost\nPoption\nKalender\nGithub\nG17 kart" | rofi -i -dmenu']' returned non-zero exit status 1.
```

**Comment by teodorlu** [comment]
Fixed in https://github.com/iterate/iterbart-rofi/commit/f5def7b157d79c37cbca78bb9164c3fe7f2a6790
